// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVGoVnvZYm5lheePNELiTFkhJfOnHQMPI',
    appId: '1:116794751297:web:672f07a2f6b80a145b89c0',
    messagingSenderId: '116794751297',
    projectId: 'messenger-app-2cde3',
    authDomain: 'messenger-app-2cde3.firebaseapp.com',
    storageBucket: 'messenger-app-2cde3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0VnATovbrl2UJ9PYW4ZnNuDooa2GCeo',
    appId: '1:116794751297:android:4a60f14a6837c7105b89c0',
    messagingSenderId: '116794751297',
    projectId: 'messenger-app-2cde3',
    storageBucket: 'messenger-app-2cde3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0CoNcLPjh5oCCtycJVrQg4li7I27K2s8',
    appId: '1:116794751297:ios:5a5eba2015eb1d2e5b89c0',
    messagingSenderId: '116794751297',
    projectId: 'messenger-app-2cde3',
    storageBucket: 'messenger-app-2cde3.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0CoNcLPjh5oCCtycJVrQg4li7I27K2s8',
    appId: '1:116794751297:ios:5a5eba2015eb1d2e5b89c0',
    messagingSenderId: '116794751297',
    projectId: 'messenger-app-2cde3',
    storageBucket: 'messenger-app-2cde3.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVGoVnvZYm5lheePNELiTFkhJfOnHQMPI',
    appId: '1:116794751297:web:f3f4adc926e3894b5b89c0',
    messagingSenderId: '116794751297',
    projectId: 'messenger-app-2cde3',
    authDomain: 'messenger-app-2cde3.firebaseapp.com',
    storageBucket: 'messenger-app-2cde3.firebasestorage.app',
  );
}
